# Generated by Django 4.1.5 on 2023-03-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_quote_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='network.quote'),
        ),
    ]
