# Generated by Django 4.1.5 on 2023-01-29 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Collectibles & Art', 'Collectibles & art'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & garden'), ('Auto Part & Accessories', 'Auto Parts & Accessories'), ('Musical instruments & gear', 'Musical instruments & gear'), ('Sporting good', 'Sporting good'), ('Toys & hobbies', 'Toys & hobbies'), ('Other categories', 'Other categories')], max_length=100)),
                ('starting_bid', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
