# Generated by Django 4.2.1 on 2023-05-15 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Collectibles & Art', 'Collectibles & art'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & garden'), ('Auto Part & Accessories', 'Auto Parts & Accessories'), ('Musical instruments & gear', 'Musical instruments & gear'), ('Sporting good', 'Sporting good'), ('Toys & hobbies', 'Toys & hobbies'), ('Other categories', 'Other categories')], max_length=100)),
                ('starting_bid', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, null=True, related_name='watchlistings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
