# Generated by Django 4.1.5 on 2023-03-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='client',
            new_name='user',
        ),
    ]
