# Generated by Django 4.2.1 on 2023-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgcategory',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imgcategory',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
