# Generated by Django 4.2.1 on 2023-05-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_imgcategory_image4_imgcategory_image5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgcategory',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='imgcategory',
            name='image5',
        ),
    ]
