# Generated by Django 4.2.1 on 2023-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_imgcategory_image4_remove_imgcategory_image5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='image1',
            new_name='image',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
