# Generated by Django 4.2.1 on 2023-08-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewed',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
