# Generated by Django 4.2.1 on 2023-08-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_recentlyviewed_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcategory',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imgcategory',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imgcategory',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
