# Generated by Django 4.2.1 on 2023-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_imgcategory_image1_alter_imgcategory_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winning_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
