# Generated by Django 4.2.1 on 2023-07-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_email_spam_email_starred_email_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailerApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
