# Generated by Django 4.2.1 on 2023-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_mailerapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailerapp',
            name='app_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
