# Generated by Django 4.2.1 on 2023-08-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_keepnotelist_keppnote_notelistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeppNote',
            new_name='KeepNote',
        ),
    ]
