# Generated by Django 4.2.1 on 2023-05-06 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_quote_reply_repost_quote_reply_quote_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.ManyToManyField(related_name='impressed_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='network.reply')),
                ('shares', models.ManyToManyField(related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='viewed_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.ManyToManyField(related_name='impressed_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='network.quote')),
                ('shares', models.ManyToManyField(related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='viewed_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.ManyToManyField(related_name='impressed_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='network.post')),
                ('shares', models.ManyToManyField(related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='viewed_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
