# Generated by Django 4.2.1 on 2023-05-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='network.chatbox'),
        ),
    ]
