# Generated by Django 4.2.1 on 2023-05-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_chatbox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='name',
            field=models.CharField(default='Chatbox', max_length=100),
        ),
    ]
