# Generated by Django 4.2.1 on 2023-05-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_chatbox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
