# Generated by Django 4.2.1 on 2023-05-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_chatbox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatbox',
            field=models.ForeignKey(default='chatbox', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='network.chatbox'),
        ),
    ]
