# Generated by Django 4.1.5 on 2023-04-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_quote_post_alter_reply_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='media',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='media',
        ),
    ]
