# Generated by Django 4.1.5 on 2023-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_media_quote_media_reply_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_quote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repost',
            name='is_repost',
            field=models.BooleanField(default=True),
        ),
    ]
