# Generated by Django 4.2.1 on 2023-05-27 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_chatbox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='user1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chexboxes_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='user2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chexboxes_as_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
